# Generated by Django 4.0.2 on 2022-07-02 17:57

from django.db import migrations

groups_names = ['manager', 'employee', 'client-manager', 'client-employee']


def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([Group(name=name) for name in groups_names])


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=groups_names).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
