# Generated by Django 4.0.2 on 2022-07-02 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='name')),
                ('status', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'In Process'), (3, 'Done')], default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('started_on', models.DateTimeField(blank=True, null=True)),
                ('finished_on', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='address')),
                ('assignees', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('contact_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='name')),
                ('status', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'In Process'), (3, 'Done')], default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('started_on', models.DateTimeField(blank=True, null=True)),
                ('finished_on', models.DateTimeField(blank=True, null=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'Flight'), (2, 'Trimming')])),
                ('assignees', models.ManyToManyField(related_name='missions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
