# Generated by Django 4.0.2 on 2022-08-08 15:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='is_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mission',
            name='is_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mission',
            name='owners',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), default=list, size=None),
        ),
        migrations.AddField(
            model_name='mission',
            name='send_notification_email',
            field=models.BooleanField(default=False),
        ),
    ]
