# Generated by Django 4.0.2 on 2022-08-11 14:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_mission_is_notification_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='owners',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None),
        ),
    ]
