# Generated by Django 4.0.2 on 2022-07-02 17:47

from django.db import migrations


def apply_migration(apps, schema_editor):
    Client = apps.get_model('clients', 'Client')
    Domain = apps.get_model('clients', 'Domain')

    tenant = Client(schema_name='public', name='public', country='DE')
    tenant.save()

    domain = Domain(domain='public', is_primary=True, tenant=tenant)
    domain.save()


def revert_migration(apps, schema_editor):
    Client = apps.get_model('clients', 'Client')
    Client.objects.filter(schema_name='public').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(apply_migration, reverse_code=revert_migration)
    ]
