# Generated by Django 4.0.2 on 2022-07-02 17:16

from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=reports.models.BaseReport.get_file_upload_path)),
                ('type', models.SmallIntegerField(choices=[(1, 'kml'), (2, 'pdf'), (3, 'xlsx')])),
                ('title', models.CharField(blank=True, max_length=256, verbose_name='title')),
                ('processed', models.BooleanField(default=False)),
                ('details', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project')),
            ],
            options={
                'ordering': ['uploaded_on'],
            },
        ),
    ]
