# Generated by Django 4.0.2 on 2023-02-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pointcloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.IntegerField()),
                ('filename', models.CharField(max_length=500)),
                ('path', models.CharField(max_length=500)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['uploaded_on'],
            },
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'kml'), (2, 'pdf'), (3, 'xlsx'), (4, 'las'), (5, 'METADATA')]),
        ),
    ]
