# Generated by Django 4.0.2 on 2022-04-13 22:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import geo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapViewConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', django.contrib.gis.db.models.fields.PointField(default=geo.models.default_map_view_center, srid=4326)),
                ('zoom', models.PositiveSmallIntegerField(default=geo.models.default_map_view_zoom)),
            ],
        )
    ]
