# Generated by Django 4.0.2 on 2022-04-13 22:17

from django.db import migrations


def create_default_map_view_conf(apps, schema_editor):
    MapViewConfiguration = apps.get_model('geo', 'MapViewConfiguration')
    MapViewConfiguration.objects.create()


def delete_default_map_view_conf(apps, schema_editor):
    MapViewConfiguration = apps.get_model('geo', 'MapViewConfiguration')
    MapViewConfiguration.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_map_view_conf, reverse_code=delete_default_map_view_conf)
    ]
