# Generated by Django 4.0.2 on 2022-07-02 17:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('reports', '0001_initial'),
        ('geo', '0003_create_default_map_view_conf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geo3DLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties', models.JSONField()),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(dim=3, geography=True, srid=4326)),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_3d_locations', to='projects.mission')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_3d_locations', to='projects.project')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Geo2DLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties', models.JSONField()),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326)),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_2d_locations', to='projects.mission')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_2d_locations', to='projects.project')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Powerline',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('geo.geo2dlocation',),
        ),
    ]
